version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  staticfiles: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  django:
    build:
      context: ../
      dockerfile: ./backend/compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    command: /gunicorn.sh
    env_file: .env
    volumes:
      - staticfiles:/staticfiles

  nginx:
    build:
      context: ../
      dockerfile: ./backend/compose/nginx/Dockerfile
    depends_on:
      - django
      - certbot
    ports:
      - "0.0.0.0:80:80"
    environment:
      - MY_DOMAIN_NAME=polynets.ca
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes_from:
      - django
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

  certbot:
    image: quay.io/letsencrypt/letsencrypt
    command: bash -c "sleep 6 && certbot certonly -n --standalone -d polynets.ca --text --agree-tos --email polinom100@gmail.com --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --keep-until-expiring --standalone-supported-challenges http-01"
    entrypoint: ""
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80"
      - "443"
    environment:
      - TERM=xterm


  redis:
    image: redis:latest
