# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('destination_country', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True, verbose_name='destination country')),
                ('seller_name', models.CharField(blank=True, max_length=255, verbose_name='seller name')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='price')),
            ],
            options={
                'verbose_name': 'deal',
                'verbose_name_plural': 'deals',
            },
        ),
    ]
