# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='image',
            field=models.URLField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
