# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20170223_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.URLField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
