# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_trip_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trip',
            new_name='Goal',
        ),
    ]
